---
- name: Download the kubectx archive.
  get_url:
    url: "{{ kubectx_download_url }}"
    dest: /tmp
    checksum: sha256:{{ kubectx_checksum_url }}
    mode: 0755
  register: kubectx_download

- name: Unarchive the kubectx archive.
  unarchive:
    src: "{{ kubectx_download.dest }}"
    dest: /tmp
    mode: 0755
    remote_src: true

- name: Copy the kubectx binary into place.
  copy:
    src: /tmp/kubectx
    dest: "{{ kubectx_bin_path }}"
    mode: 0755
    remote_src: true
  become: true
