---
- name: Check the presence of the kubectx binary.
  stat:
    path: "{{ kubectx_bin_path }}"
  register: kubectx_check

- name: Check the kubectx version.
  shell: "{{ kubectx_bin_path }} --version"
  failed_when: false
  changed_when: false
  register: kubectx_current_version

- name: Install kubectx v{{ kubectx_version }}
  include_tasks: install.yml
  when: >-
    not kubectx_check.stat.exists
    or kubectx_version not in kubectx_current_version.stdout
